# downloader.sh
# Version 1.0 April 15 2021
# Charlie Gerrie

# Should be run in the folder containing gennedList.txt, which is generated by lister.sh
list_file=gennedList.txt

while read in
do
	# parse n and id
	n=${in:0:4}
	id=${in:5:11}
	date="$(youtube-dl -q -j "https://www.youtube.com/watch?v=$id" | cut -c18-25)"

	if [ -n "$date" ]
	then
		date_iso="${date:0:4}-${date:4:2}-${date:6:2}"
		echo -e "$n\t$date_iso"
	fi
done < $list_file
